[package]
name = "satisfactory-flow-synthetizer"
version.workspace = true
description = "Exact Satisfactory flow synthetizer"
edition.workspace = true
license.workspace = true

[lib]
name = "satisfactory_flow_synthetizer_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
synthetizer-app = { path = "../crates/synthetizer-app" }
rusqlite = { version = "0.38", features = ["bundled"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.151"
solver-validation = { path = "../crates/solver-validation" }
solver-api = { path = "../crates/solver-api" }
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tempfile = "3.23"
uuid = { version = "1.18", features = ["serde", "v4"] }

[lints]
workspace = true
