[package]
name = "solver-z3"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
solver-api = { path = "../solver-api" }
solver-validation = { path = "../solver-validation" }
num = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
z3 = { version = "0.20.2", features = ["bundled", "num"] }

[dev-dependencies]
serde_json = "1.0"

[lints]
workspace = true

